USE demo;


CREATE TABLE IF NOT EXISTS airlines (
  IATA_CODE VARCHAR(10) NULL,
  AIRLINE   VARCHAR(255) NULL
);

TRUNCATE TABLE airlines;

LOAD DATA INFILE '/var/lib/mysql-files/airlines.csv'
INTO TABLE airlines
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(IATA_CODE, AIRLINE);


CREATE TABLE IF NOT EXISTS flights (
  YEAR                INT         NULL,
  MONTH               INT         NULL,
  DAY                 INT         NULL,
  DAY_OF_WEEK         INT         NULL,
  AIRLINE             VARCHAR(10) NULL,
  FLIGHT_NUMBER       INT         NULL,
  TAIL_NUMBER         VARCHAR(20) NULL,
  ORIGIN_AIRPORT      VARCHAR(10) NULL,
  DESTINATION_AIRPORT VARCHAR(10) NULL,
  SCHEDULED_DEPARTURE INT         NULL,
  DEPARTURE_TIME      INT         NULL,
  DEPARTURE_DELAY     INT         NULL,
  TAXI_OUT            INT         NULL,
  WHEELS_OFF          INT         NULL,
  SCHEDULED_TIME      INT         NULL,
  ELAPSED_TIME        INT         NULL,
  AIR_TIME            INT         NULL,
  DISTANCE            INT         NULL,
  WHEELS_ON           INT         NULL,
  TAXI_IN             INT         NULL,
  SCHEDULED_ARRIVAL   INT         NULL,
  ARRIVAL_TIME        INT         NULL,
  ARRIVAL_DELAY       INT         NULL,
  DIVERTED            TINYINT     NULL,
  CANCELLED           TINYINT     NULL,
  CANCELLATION_REASON VARCHAR(10) NULL,
  AIR_SYSTEM_DELAY    INT         NULL,
  SECURITY_DELAY      INT         NULL,
  AIRLINE_DELAY       INT         NULL,
  LATE_AIRCRAFT_DELAY INT         NULL,
  WEATHER_DELAY       INT         NULL
);

TRUNCATE TABLE flights;

LOAD DATA INFILE '/var/lib/mysql-files/flights.csv'
INTO TABLE flights
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  @YEAR,
  @MONTH,
  @DAY,
  @DAY_OF_WEEK,
  @AIRLINE,
  @FLIGHT_NUMBER,
  @TAIL_NUMBER,
  @ORIGIN_AIRPORT,
  @DESTINATION_AIRPORT,
  @SCHEDULED_DEPARTURE,
  @DEPARTURE_TIME,
  @DEPARTURE_DELAY,
  @TAXI_OUT,
  @WHEELS_OFF,
  @SCHEDULED_TIME,
  @ELAPSED_TIME,
  @AIR_TIME,
  @DISTANCE,
  @WHEELS_ON,
  @TAXI_IN,
  @SCHEDULED_ARRIVAL,
  @ARRIVAL_TIME,
  @ARRIVAL_DELAY,
  @DIVERTED,
  @CANCELLED,
  @CANCELLATION_REASON,
  @AIR_SYSTEM_DELAY,
  @SECURITY_DELAY,
  @AIRLINE_DELAY,
  @LATE_AIRCRAFT_DELAY,
  @WEATHER_DELAY
)
SET
  YEAR                = NULLIF(@YEAR,''),
  MONTH               = NULLIF(@MONTH,''),
  DAY                 = NULLIF(@DAY,''),
  DAY_OF_WEEK         = NULLIF(@DAY_OF_WEEK,''),
  AIRLINE             = NULLIF(TRIM(@AIRLINE),''),
  FLIGHT_NUMBER       = NULLIF(@FLIGHT_NUMBER,''),
  TAIL_NUMBER         = NULLIF(TRIM(@TAIL_NUMBER),''),
  ORIGIN_AIRPORT      = NULLIF(TRIM(@ORIGIN_AIRPORT),''),
  DESTINATION_AIRPORT = NULLIF(TRIM(@DESTINATION_AIRPORT),''),
  SCHEDULED_DEPARTURE = NULLIF(@SCHEDULED_DEPARTURE,''),
  DEPARTURE_TIME      = NULLIF(@DEPARTURE_TIME,''),
  DEPARTURE_DELAY     = NULLIF(@DEPARTURE_DELAY,''),
  TAXI_OUT            = NULLIF(@TAXI_OUT,''),
  WHEELS_OFF          = NULLIF(@WHEELS_OFF,''),
  SCHEDULED_TIME      = NULLIF(@SCHEDULED_TIME,''),
  ELAPSED_TIME        = NULLIF(@ELAPSED_TIME,''),
  AIR_TIME            = NULLIF(@AIR_TIME,''),
  DISTANCE            = NULLIF(@DISTANCE,''),
  WHEELS_ON           = NULLIF(@WHEELS_ON,''),
  TAXI_IN             = NULLIF(@TAXI_IN,''),
  SCHEDULED_ARRIVAL   = NULLIF(@SCHEDULED_ARRIVAL,''),
  ARRIVAL_TIME        = NULLIF(@ARRIVAL_TIME,''),
  ARRIVAL_DELAY       = NULLIF(@ARRIVAL_DELAY,''),
  DIVERTED            = NULLIF(@DIVERTED,''),
  CANCELLED           = NULLIF(@CANCELLED,''),
  CANCELLATION_REASON = NULLIF(TRIM(@CANCELLATION_REASON),''),
  AIR_SYSTEM_DELAY    = NULLIF(@AIR_SYSTEM_DELAY,''),
  SECURITY_DELAY      = NULLIF(@SECURITY_DELAY,''),
  AIRLINE_DELAY       = NULLIF(@AIRLINE_DELAY,''),
  LATE_AIRCRAFT_DELAY = NULLIF(@LATE_AIRCRAFT_DELAY,''),
  WEATHER_DELAY       = NULLIF(@WEATHER_DELAY,'');
